on:
  schedule:
    - cron:  '0 10 * * *'
    # This runs at 10:00 AM UTC each day.
    # * is a special character in YAML so you have to quote this string
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install withings-sync

      - name: write config file
        run: |

          cat <<EOF > $HOME/.withings_user.json
          {
            "authentification_code": "2d700940db825ec934e2df8f44bcf57fcff223b4"
          }
          EOF

      - name: execute py script # run main.py
        run: withings-sync -f 2024-04-01 -v
    
